# -*- coding: utf-8 -*-
"""Linguagem de programação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pP37xY2h3VdsSjm3Kpko-2jQEbnIyOq

U2_A2
"""

# Importe as bibliotecas necessárias

import numpy as np

# Dados dos participantes

participantes = [
    {
        "nome": "Alice",
        "localizacao": "EUA",
        "afiliacao": "Universidade A",
        "interesses": ["Fisica", "Astronomia"]
    },

    {
        "nome": "Bob",
        "localizacao": "Brasil",
        "afiliacao": "Instituto B",
        "interesses": ["Biologia", "Astronomia"]
    },

    {
        "nome": "Charlie",
        "localizacao": "Índia",
        "afiliacao": "Instituto C",
        "interesses": ["Química", "Engenharia"]
    }

# Adicione mais participantes conforme necessário
]

# Usando sets para identificar diferenrtes regiões dos participantes

regioes = set(participante["localizacao"] for participante in participantes)

# Usando um dicionário para categorizar afiliações

afiliacoes = {}
for participante in participantes:
  afiliacao = participante["afiliacao"]
  if afiliacao not in afiliacoes:
   afiliacoes[afiliacao] = []
  afiliacoes[afiliacao].append(participante["nome"])

# Usando NumPy para analisar áreas de interesse

areas_de_interesse = np.array([interesse for participante in participantes for interesse in participante ["interesses"]])
interesses_unicos, contagem = np.unique(areas_de_interesse, return_counts=True)
area_mais_popular = interesses_unicos[np.argmax(contagem)]

# Resultados

print("Regiões dos participantes: " ,regioes)
print("Afiliações dos participantes: ")
for afiliacao, nomes in afiliacoes.items():
 print(f"{afiliacao}: {','.join(nomes)}")
print("Área de interesse mais popular: ", area_mais_popular)

# Resultado:

#Teste: Adicionando e atribuindo novos valores

novo_dic = {15,20,30,40,50}
print(f"Valores adicionados inicialmente: ", novo_dic)
novo_dic = (25,35,45,55)
print(f"Novos valores atribuidos: ", novo_dic)

#Exemplo 1 - Criação de um dicionário vazio, seguido de adtribiução de chaves e valores

dici_1 = {}
dici_1['nome'] = "Maria"
dici_1['idade'] = 25

#Exemplo 2 - Criação de um dicionário com prares chave valor

dici_2 = {'nome':'Maria', 'idade':25}

#Exemplo 3 - Criação de um dicionário com uma lista de tuplas representando pares chave:valor

dici_3 = dict([('nome', "Maria"),('idade',25)])

#Exemplo 4 - Criação de um dicionário usando a função built-in zip() e duas listas, uma para as chaves e outra para os valores

dici_4 = dict(zip(['nome', 'idade'], ["Maria",25]))

#Teste de todas as contruções resultam em objetos iguais

print(dici_1 == dici_2 == dici_3 == dici_4)
print(dici_1)

#Deve imprimir True

#Criando um conjunto vazio

meu_conjunto = set()

#Adicionando elementos ao conjunto

meu_conjunto.add(10)
meu_conjunto.add(15)
meu_conjunto.add(30)

#Imprimindo o conjunto

print("Conjunto após adicionar elementos: ", meu_conjunto)

#Verificando se um elemento está no conjunto

elemento = 20
if elemento in meu_conjunto:
  print(f"{elemento} está no conjunto.")
else:
    print(f"{elemento} não está no conjunto.")

#Removendo elemento do conjunto

meu_conjunto.remove(15)

#Imprimindo o conjunto atualizado

print("Conjunto após remover o elemento 15: ", meu_conjunto)

"""U2_A1

map()
"""

precos_em_dolares = [100,50,75,120]
taxa_de_cambio = 5.25
precos_em_reais = list(map(lambda x:x * taxa_de_cambio, precos_em_dolares))
print(precos_em_reais)

numeros = [1,2,3,4,5,6,7,8,9,10]
numeros_pares = list(filter(lambda x: x % 2 == 0, numeros))
print(numeros_pares)

"""List comprehensions"""

linguagens = ['PYTHON', 'JAVA','JAVASCRIPT','C','C#','C++','SWIFT','GO']
print('Antes da listcomp =', linguagens)
linguagens = [item.lower() for item in linguagens]
print('\nDepois da listcomp = ', linguagens)

"""Listas"""

cores = ['vermelho','verde','azul','amarelo','roxo']
for cor in cores:
  print(f'Posição = {cores.index(cor)} = {cor}')

"""Sequência"""

texto = "Explorando a diversidade de linguagens de programação."

print(f"Tamanho do texto = {len(texto)}")
print(f"Python in texto = {'Python' in texto}")
print(f"Quantidade de e no texto = {texto.count('e')}")
print(f'As 5 primeiras letras são: {texto[:5]}')

"""U1_A5"""

# Lista de notas dos estudantes

notas = [7.5, 8.0, 6.5, 9.0, 7.0]


# Função regular para calcular a média

def calcular_media(notas):

 total = sum(notas)

 media = total / len(notas)
 return media


# Função lambda para arredondar a média para duas casas decimais

 arredondar_media = lambda media: round(media, 2)


# Calcular a média

 media = calcular_media(notas)

 media_arredondada = arredondar_media(media)


# Verificar se os estudantes foram aprovados

 situacao = "Aprovado" if media_arredondada >= 7 else "Reprovado"


# Resultados

print(notas)
print(media_arredondada)
print(situacao)

#Funções definidas por mim.
def calcular_desconto (valor, percentual):
#Calcula o valor final aplicando um desconto percentual.
    if percentual < 0 or percentual > 100:
      return None #marcação inválida
    desconto = valor * (percentual/100)
    return valor - desconto

def registrar_venda(produto, valor_final):
#Imprime registro de venda.
    print(f"Venda registrada: {produto} por R$ {valor_final:.2f}")


#Função lambda para arrendondar
arredondar = lambda v: round(v,2)

#Variáveis principais do PDV
total_vendas = 0
qtd_vendas = 0

#Loop principal do caixa. MINHALOJAPDV
while True:
  print("\n ----- Minha Loja. ----- PDV -----")
  print("1 - Registrar venda.")
  print("2 - Ver relatório de vendas.")
  print("0 - Encerrar caixa.")
  opcao = input("Escolha a opção desejada: ")

  if opcao == "0":
    print("Encerrando o caixa. Até Amanhã")
    break

  elif opcao == "1":
    produto = input("Digite o nome do produto: ")
    valor = float(input("Valor do produto: R$" ))
    percentual = float(input("Desconto (%): "))

    valor_final = calcular_desconto(valor,percentual)

    if valor_final is None:
      print("Desconto inválido! Use um valor entre 0 e 100.")
    else:
      valor_final = arredondar(valor_final)
      registrar_venda(produto, valor_final)
      total_vendas = total_vendas + valor_final
      qtd_vendas = qtd_vendas + 1

  elif opcao == "2":
      print(f"\nVendas hoje: {qtd_vendas}")
      print(f"Total faturado: R$ {arredondar(total_vendas)}")
  else:
    print("Opção inválida. Tente novamente. ")

"""U1_A4"""

def calcular_area(base, altura):
  area = base * altura
  return area

resultado = calcular_area(8, 5)
print(resultado)

numeros = [1, 2, 3, 4, 5]
comprimento = len(numeros)
print(comprimento)

def soma(a,b):
  resultado = a + b
  return resultado
resultado_soma = soma(5,3)
print(resultado_soma)

def e_par(numero):
  if numero %2 == 0:
    return True
  else:
    return False

numero = 1653
if e_par(numero):
  print(f"{numero} é um número par.")
else:
    print(f"{numero} não é um número par")

"""U1_A3"""

numeros = [1,2,3,4,5,6]

for numeros in numeros:
  print(numeros)

filmes = ["Filme 1 ", "Filme 2 ", "Filme 3 ", "Filme 4 ", "Filme 5 "]
print("Bem-vindo a classificação de filmes")
print("Você tem 5 filmes para classificar")
print("Digite '0' a qualquer momento para sair")

for filme in filmes:
  classificacao = input(f"Como voce classifica '{filme}' de 1 a 5 (Ou 0 para sair): ")
  if classificacao == '0':
    print ("Que pena")
    break

  classificacao = int(classificacao)
  if classificacao <1 or classificacao >5:
    print ("Nota inválida")
  else:
    print (f"Você classificou '{filme}' com '{classificacao}' estrelas.\n")
  print("Obrigado por votar\n")

5filmes = ["1", "2", "3" ,"4" ,"5" ]


print()

print()

print()


for filme in filmes:

 while True:

   classificacao = input(f"{filme}' de 1 a 5? (ou 0 para parar): ")

if classificacao == '0':

 print(f"{filme}' interrompida.")
 break

classificacao = int(classificacao)

if classificacao < 1 or classificacao > 5:

 print()

else:

 print(f"{filme}' com {classificacao} estrelas.\n")
 break # Sai do loop interno


print()

copo = 0
while copo < 5:
  copo += 1
  print(f"Copo no nível {copo}")

for i in range(5):
    print(i)

"""U1_A2"""

#Máquina de venda automática de ingressos de cinema:
#Solicita a idade do cliente

idade = int(input("Por favor, digite sua idade: "))
if idade < 12:
  print("Recomendamos o filme infantil FILME 1.")
elif 12 <= idade <18:
  print("Recomendamos o filme adolescente FILME 2.")
else:
  print("Recomendamos o emocionante FILME 3.")

#Verfica a disponibilidade de ingressos

quantidade_de_ingressos = 10
if quantidade_de_ingressos > 0:
  print("INGRESSOS DISPONÍVES. DIVIRTA-SE NO CINEMA!")
else:
  print("DESCULPE, TODOS OS INGRESSOS FORAM VENDIDOS")

idade = int(input("DIGITE SUA IDADE: "))
if idade < 18:
  print("MENOR DE IDADE")
elif idade >= 18 and idade <= 65:
  print ("ADULTO")
else:
  print("IDOSO")

"""U1_A1"""

def calcular_media (notas, divisao):
    media = notas / divisao
    return media

media = calcular_media(Nota1+Nota2+Nota3+Nota4+Nota5, divisao)




Nota1 = int(input("DIGITE A NOTA1: "))
Nota2 = int(input("DIGITE A NOTA2: "))
Nota3 = int(input("DIGITE A NOTA3: "))
Nota4 = int(input("DIGITE A NOTA4: "))
Nota5 = int(input("DIGITE A NOTA5: "))

print(Media)
if Media >= 7:
    situacao = "Aprovado"
else:
    situacao = "Reprovado"

print(f'{situacao}')

def calcular_media (notas, divisao)
    media = notas / divisao
    return media

media = calcular_media(Nota1)




Nota1 = int(input("DIGITE A NOTA1: "))
Nota2 = int(input("DIGITE A NOTA2: "))
Nota3 = int(input("DIGITE A NOTA3: "))
Nota4 = int(input("DIGITE A NOTA4: "))
Nota5 = int(input("DIGITE A NOTA5: "))

Media = (Nota1+Nota2+Nota3+Nota4+Nota5)/5
print(Media)
if Media >= 7:
    situacao = "Aprovado"
else:
    situacao = "Reprovado"

print(f'{situacao}')